### PR TITLE
Fix the issue related to timestamps.

### PR DESCRIPTION
**Pull request by mortaliorchard**
The dev local machine timestamp isn't UTC, so this method was properly working,
but looking at loggly, you couldn't see the logs as being part of the last
10 minutes (or so).

@rantonmattei

### CODE REVIEW

**Comment by rantonmattei** [comment]
R+

**Comment by rantonmattei** [comment]
Actually, can't we do shorter?
`time.gmtime(seconds))`
https://docs.python.org/3.4/library/time.html?highlight=gmtime#time.gmtime

**Comment by rantonmattei** [comment]
Here is my proposed implementation:
```python
import time

# ...

utc_timestamp = time.gmtime(record.created)
utc_datetime = datetime.datetime.fromtimestamp(utc_timestamp)
# ...
    'timestamp': utc_datetime.isoformat(),
# ...
```

Non-blocking. Yours can go I guess if you have limited time.

R+

**Comment by mortaliorchard** [comment]
Strangely, `time.gmtime` shows an hour ahead of actual GMT.

**Comment by rantonmattei** [comment]
R++

**Pull request merged**
