### PR TITLE
Fixed wrong log level sequence

### PR DESCRIPTION
**Pull request by jian-wu**
@azinger-theorchard @csmall01 please review

/cc @mortaliorchard @jessmchung @mymac80

### CODE REVIEW

**Comment by mortaliorchard** [comment]
You need to update the tests to reflect this change.

**Comment by jessmchung** [comment]
@jian-wu Great catch, thank you! Can you update the unit test?

**Comment by jian-wu** [comment]
Unit tests fixed.

**Comment by mortaliorchard** [comment]
R+

**Comment by jessmchung** [comment]
R+ Thank you!!!

**Pull request merged**
